services:

  database:
    container_name: fast_api_geek_uni_db_sec06
    image: postgres:15.1
    restart: 'no'
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=university
      - POSTGRES_USER=geek
      - POSTGRES_DB=startup
    ports:
      - 5432:5432

volumes:
  pg_data:
